modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "mcft"
version = "${version}"
displayName = "MCFaceTracking"
authors = "squi2rel"
description = '''
Face Tracking for Minecraft
'''
#logoFile = ""

[[dependencies.mcft]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
