modLoader = "javafml"
loaderVersion = "[6,7)"
issueTrackerURL = "https://github.com/squi2rel/MCFaceTracking/issues"
license = "MIT"

[[mods]]
modId = "mcft"
version = "${version}"
displayName = "MCFaceTracking"
authors = "squi2rel"
description = '''
Face Tracking for Minecraft
'''
logoFile = "assets/mcft/icon.png"

[[dependencies.mcft]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,21.5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mcft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,1.21.5)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "mcft.mixins.json"
